server:
  port: 8080
spring:
  application:
    name: bone-provider
    jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  path: /apply/logs/${BONE_EUREKA_SERVER_ENV:default}/${spring.application.name:app}/${HOSTNAME:local}
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type.descriptor.sql.BasicExtractor: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://bone:123456@192.168.200.64:30082/eureka/
  instance:
    prefer-ip-address: true
