spring:
  # 配置注册中心安全账户
  security:
    user:
      name: ${SECURITY_USERNAME:bone}
      password: ${SECURITY_PASSWORD:123456}
      
  # 配置RabbitMQ,用于应用配置项通知
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: liuqi
      
# 注册中心配置
eureka:
  #See org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
  client:
    # 拉取节点注册信息的时间间隔,CacheRefreshThread的调度频率,默认30
    registry-fetch-interval-seconds: 1
    serviceUrl:
      # 默认注册中心地址
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8671/eureka/

  #See org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean
  instance:
    # Eureka Client间隔多久向Eureka Server发送心跳来感知该实例还存活(服务端在该时间段内没有收到心跳则删除该实例),默认90
    lease-expiration-duration-in-seconds: 30
    # Eureka Client向Eureka Server发送心跳的时间间隔,默认30
    lease-renewal-interval-in-seconds: 10
    
# 断路器的配置
hystrix:
  command:
    # default配置全局HystrixCommand
    default:
      # 线程执行的超时时间,默认值1000
      execution.isolation.thread.timeoutInMilliseconds: 600000
      # 线程执行的隔离策略,默认值THREAD|SEMPHORE
      execution.isolation.strategy: THREAD
      
#Ribbon的配置
ribbon:
  # 开启饥饿加载,默认false
  eager-load:
    enabled: true
  # 配置Ribbon默认的连接超时时间，默认1000
  ConnectTimeout: 3000
  # 配置Ribbon默认的读超时时间，默认1000
  ReadTimeout: 30000
  # 同一个服务重试的次数(除去第一次)，默认值 0
  MaxAutoRetries: 1
  # 重试下一个服务的最大数量(除去第一个服务)，默认值 1
  MaxAutoRetriesNextServer: 0
