spring:
  # 配置注册中心安全账户
  security:
    user:
      name: bone
      password: 123456
      
  # 配置RabbitMQ,用于应用配置项通知
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: liuqi
      
# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/}
