spring:
  security:
    user:
      name: bone
      password: 123456
      
  #配置链路追踪
  zipkin:
    sender:
      type: web
    locator:
      discovery:
        # 启用从注册中心获取Zipkin Server地址，如果为true，则spring.zipkin.baseUrl为服务名称
        enabled: true
    # 指定Zipkin Server地址，如果spring.zipkin.locator.discovery.enabled为true，则为服务名称，否则为Zipkin Server的URL地址
    base-url: bone-cloud-zipkin-server
  #配置采样率
  sleuth:
    sampler:
      probability: ${BONE_SLEUTH_PROBABILITY:1.0}

  #配置RabbitMQ,用于应用配置项通知
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: liuqi
    
#Eureka的配置    
eureka:
  client:
    # 注册自身节点
    register-with-eureka: true
    # 拉取节点注册信息
    fetch-registry: true
  instance:
    #优先使用IP地址进行注册
    prefer-ip-address: true
    instance-id: ${HOSTNAME:localhost}:${server.port}
    #Eureka Client间隔多久向Eureka Server发送心跳,告知Eureka Server自己还存活,默认90
    leaseExpirationDurationInSeconds: 15
    #Eureka Client向Eureka Server发送心跳的时间间隔,默认30
    leaseRenewalIntervalInSeconds: 5
    # 实例状态信息的URL路径
    status-page-url-path: "/actuator/info"
    # 实例健康信息的URL路径
    health-check-url-path: "/actuator/health"
    
#Ribbon的配置
ribbon:
  # 饥饿加载服务实例，默认是false
  eager-load:
    enabled: true

# 启用Hystrix
feign:
  hystrix:
    enabled: true

# 监控端点权限
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
