spring:
  # 配置注册中心安全账户
  security:
    user:
      name: ${SECURITY_USERNAME:bone}
      password: ${SECURITY_PASSWORD:123456}
  # 配置链路追踪
  zipkin:
    sender:
      type: web
    locator:
      discovery:
        # 是否启用服务发现,默认false
        enabled: true
    # 如果启用服务发现，则spring.zipkin.baseUrl为http://网关名/服务名称;如果不启用则为http://zipkin-server地址/
    base-url: http://zuul-server/zipkin-server
  # 配置采样率
  sleuth:
    sampler:
      probability: ${SLEUTH_PROBABILITY:1.0}

#Eureka的配置    
eureka:
  environment: ${env:local}
  #See org.springframework.cloud.netflix.eureka.EurekaClientConfigBean
  client:
    # 注册自身节点
    register-with-eureka: true
    # 拉取节点注册信息
    fetch-registry: true
    serviceUrl:
      # 默认注册中心地址
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8671/eureka/

  #See org.springframework.cloud.netflix.eureka.EurekaInstanceConfigBean
  instance:
    #优先使用IP地址进行注册
    prefer-ip-address: true
    # 实例ID
    instance-id: ${HOSTNAME:localhost}:${server.port}
    #Eureka Client间隔多久向Eureka Server发送心跳,告知Eureka Server自己还存活,默认90
    leaseExpirationDurationInSeconds: 15
    #Eureka Client向Eureka Server发送心跳的时间间隔,默认30
    leaseRenewalIntervalInSeconds: 5
    # 实例状态信息的URL路径
    status-page-url-path: "/actuator/info"
    # 实例健康信息的URL路径
    health-check-url-path: "/actuator/health"

#断路器的配置
hystrix:
  command:
    # default配置全局HystrixCommand
    default:
      # 线程执行的超时时间,默认值1000
      execution.isolation.thread.timeoutInMilliseconds: 2000
      # 线程执行的隔离策略,默认值THREAD|SEMPHORE
      execution.isolation.strategy: THREAD

#Ribbon的配置
ribbon:
  # 开启饥饿加载,默认false
  eager-load:
    enabled: true
  # 配置Ribbon默认的连接超时时间，默认1000
  ConnectTimeout: 1000
  # 配置Ribbon默认的读超时时间，默认1000
  ReadTimeout: 1000
  # 同一个服务重试的次数(除去第一次)，默认值 0
  MaxAutoRetries: 0
  # 重试下一个服务的最大数量(除去第一个服务)，默认值 1
  MaxAutoRetriesNextServer: 1

# 启用Feign的Hystrix
feign:
  hystrix:
    enabled: true

# 管理监测端口(暂时放开)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"