eureka:
  server:
    ################注册中心节点和客户端节点间配置################
    # 是否开启自我保护
    enable-self-preservation: false
    # 清理无效注册节点的时间间隔
    eviction-interval-timer-in-ms: 5000
    # 清理过期数据的时间间隔
    delta-retention-timer-interval-in-ms: 5000
    # 不提供过期数据给客户端
    disable-delta: false
    # 使用ReadOnlyCache缓存注册节点信息
    use-read-only-response-cache: true
    # 清除ReadOnlyCache缓存中过期注册节点信息的时间间隔
    response-cache-auto-expiration-in-seconds: 60
    # 更新ReadOnlyCache缓存中注册节点信息的时间间隔
    response-cache-update-interval-ms: 10000

    ################注册中心节点和节点间配置################
    # 启用节点间复制的最少可用实例个数
    min-available-instances-for-peer-replication: 3
    # 实例间复制信息的最长时间
    max-time-for-replication: 10000
    # 实例间复制信息的最小线程数量
    min-threads-for-peer-replication: 2
    # 实例间复制信息的最大线程数量
    max-threads-for-peer-replication: 2
    # 实例更新数据信息的时间间隔
    peer-eureka-nodes-update-interval-ms: 60000
    # 实例刷新状态信息的时间间隔
    peer-eureka-status-refresh-time-interval-ms: 30000