server:
  port: 5551
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring_cloud?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: liuqi

zuul:
  routes:
    consumer-movie:
      path: /client/**
      serviceId: consumer-movie

#安全配置
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:7771/uaa/oauth/token
      user-authorization-uri: http://localhost:7771/uaa/oauth/authorize
      #授权端点
      # OAuth客户端ID
      client-id: zuul_server
      # OAuth客户端密钥
      client-secret: secret
    resource:
      jwt:
        # 使用对称加密方式,默认算法为HS256
        key-value: secret