server:
  port: 8741
#安全配置
security:
  oauth2:
    client:
      #授权
      client-id: ${spring.application.name}
      client-secret: secret
    resource:
      jwt:
        key-value: springcloud123
