server:
  port: 8012
spring:
  application:
    name: provider-user
  security:
    user:
      name: bone
      password: 123456
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type.descriptor.sql.BasicExtractor: DEBUG
