eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://bone:123456@localhost:8761/eureka/}
  instance:
    #优先使用IP地址进行注册
    prefer-ip-address: true
    #Eureka Client间隔多久向Eureka Server发送心跳,告知Eureka Server自己还存活,默认90
    leaseExpirationDurationInSeconds: 15
    #Eureka Client向Eureka Server发送心跳的时间间隔,默认30
    leaseRenewalIntervalInSeconds: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"    
logging:
  level:
    root: info
